language: node_js
node_js:
  - v7
  - v6
  - v5
  - v4
  - '0.12'
before_install:
  - openssl aes-256-cbc -K $encrypted_88d079db7ad0_key -iv $encrypted_88d079db7ad0_iv -in deploy_key.enc -out deploy_key -d
  - rm deploy_key.enc # Don't need it anymore
  - chmod 600 deploy_key
  - mv deploy_key ~/.ssh/id_rsa
script:
  - npm test
after_success:
  - bash .deploy.sh
